[app]
title = "Main system HUB ðŸ¦€"

[[categories]]
name = "System"

[[categories.commands]]
name = "ðŸ”‚ Update System"
command = "./src/scripts/update.sh"

[[categories.commands]]
name = "ðŸ§¹ Clean Pacman&Paru Cache"
command = "./src/scripts/scc.sh"

[[categories.commands]]
name = "ðŸª  Clean RAM"
command = "sudo sync; sudo sysctl -w vm.drop_caches=3"

[[categories]]
name = "Personalization"

[[categories.commands]]
name = "ðŸŽ¨ Change Theme"
command = "echo 'Theme changer coming soon'"
