[app]
title = "Main system HUB ðŸ¦€"

[[categories]]
name = "System"

[[categories.commands]]
name = "ó°š° Update System"
command = "./src/scripts/update.sh"

[[categories.commands]]
name = "îª Trash Cleanup"
command = "trash-empty"

[[categories.commands]]
name = "î¸¦ Clean Pacman&Paru Cache"
command = "./src/scripts/scc.sh"

[[categories.commands]]
name = "î¿… Clean RAM"
command = "sudo sync; sudo sysctl -w vm.drop_caches=3"

[[categories.commands]]
name = "ïƒ‡ Disk Analysis"
command = "dua i ~/"

[[categories]]
name = "Personalization"

[[categories.commands]]
name = "ó°¸‰ Change Wallpaper"
command = "./src/scripts/change_wallpaper.sh"

[[categories.commands]]
name = "ï³ Qt6 Theme Control"
command = "nohup qt6ct >/dev/null 2>&1 &"

[[categories.commands]]
name = "ï¡ GTK Theme Control"
command = "nohup nwg-look >/dev/null 2>&1 &"

[[categories]]
name = "Development"

[[categories.commands]]
name = "îœ‚ Sync dot files"
command = "~/GitStuff/UA-dot/sync.sh"
